import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RoomMenuBar from "@/components/RoomMenuBar";
import { getRooms } from "@/lib/rooms";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Hero image – full width, 30vh tall */}
        <div className="relative w-full h-[30vh]">
          <Image
            src="/hero.jpg"
            width="1280"
            height="420"
            alt=""
            className="w-full h-full object-cover"
          />

          <div className="absolute inset-0 flex items-center justify-center">
            <div className="bg-black px-12 py-6">
              <h1 className="text-white text-3xl md:text-5xl font-semibold tracking-wide">
                Bienvenue
              </h1>
            </div>
          </div>
        </div>

        <RoomMenuBar rooms={await getRooms()} />

        {children}
      </body>
    </html>
  );
}
